### ISSUE TITLE
Feature request: Singe-file Lona apps.

### ISSUE THREAD

**Issue by laundmo** [fscherf/lona#2]
Is it possible to make a Lona app in a single file? 

For trying out the framework or small quick-n-dirty projects, setting up an entire project tree seems excessive.

**Comment by fscherf** [comment]
Me too :D 

So! I thought of something like this:

```python
from lona.html import HTML, H1, P
from lona.view import LonaView
from lona import Lona

app = Lona(__file__)

app.settings.MAX_WORKER_THREADS = 10

@app.middleware
class Middleware:
    def handle_request(self, data):
        return data


@app.add_template('lona/frontend.html', """
    <h1>Frontend</h1>
""")


@app.route('/')
class Home(LonaView):
    def handle_request(self, request):
        return HTML(
            H1('Hello World'),
            P('Lorem Ipsum')
        )


app.run(port=8080, shell=True)
```

**Comment by laundmo** [comment]
LGTM

except for the fact add_template is using decorator syntax. why?

**Comment by fscherf** [comment]
whoops. that was a typo. fixed!

The middleware is not needed, but thats the api if you want to add one

**Comment by laundmo** [comment]
i see, looks good

wonder whether it would be easier to do the routing without a decorator, just passing a dictionary of routes and classes later.

**Comment by laundmo** [comment]
i was more suggesting something along the lines of ```py
class Home(LonaView):
    def handle_request(self, request):
        return HTML(
            H1('Hello World'),
            P('Lorem Ipsum')
        )
        
app.routes({
    "/": Home
})
```

**Comment by fscherf** [comment]
Routing tables cant be represented by dicts, because routes can have a specific order. Keyword args for routes have to be supported too. Additionally i can support this syntax

```python
class HomeView(LonaView):
    def handle_request(self, request):
        return '<h1>Hello World</h1>'


app.routes = [
    Route('/', HomeView, interactive=False),
]

```

**Comment by laundmo** [comment]
If you are supporting anything older than 3.6 that's correct, but 3.6 onward dicts keep their order.
It's not really documented anywhere which versions of python 3 lona supports, so I'm not sure whether it would be okay to rely on that.

**Comment by fscherf** [comment]
I think a list is least surprising for a routing table. I will support both methods of adding a view

**Comment by laundmo** [comment]
I think we've been bikeshedding for long enough, do whatever you think makes most sense.

**Comment by fscherf** [comment]
@laundmo done! Lona scripts are available in Lona 1.1. Checkout https://lona-web.org/end-user-documentation/lona-scripts.html

**Comment by laundmo** [comment]
looks good!

would you consider making the example in the readme and at the start of the
docs single file scripts?

**Comment by fscherf** [comment]
You like the click example better than the clock example?

**Comment by laundmo** [comment]
oh im sorry, apparently i had to refresh the readme.

in the docs under basic concept would be another good spot for a single
file script, right?

**Comment by fscherf** [comment]
Good idea. I will do that soon. Can i close this issue?

**Comment by laundmo** [comment]
go ahead!
